# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Hydrogen Reviews"
client_id = "c0116ccf9fafb79e22c1a9dcfbb968fd"
application_url = "https://strings-ignored-smooth-review.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://strings-ignored-smooth-review.trycloudflare.com/auth/callback",
  "https://strings-ignored-smooth-review.trycloudflare.com/auth/shopify/callback",
  "https://strings-ignored-smooth-review.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://strings-ignored-smooth-review.trycloudflare.com/app-proxy"
subpath = "hydrogen-reviews"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hydrogen-starter.myshopify.com"
